### ISSUE TITLE
Problemas con Push

### ISSUE THREAD

**Issue by DiegoVillegasA** [ITAM-DS/mate-computacional#119]
Hola, oye quería subir la tarea, pero, erróneamente, únicamente tecleé:

git push

Cuando quiero hacer el pull request me aparece que te enviarán como 340 archivos modificados por no especificar a qué lo quería hacer push...

¿Hay alguna forma de revertir el push para únicamente mandarte la tarea corregida?

**Comment by DiegoVillegasA** [comment]
Por si alguien tiene el mismo problema, lo resolví con:

git reset --hard HEAD@{1}
git push -f
git reset --hard HEAD@{1}

**Comment by nanounanue** [comment]
Muchas gracias!
