### ISSUE TITLE
Archivo ridículamente grande

### ISSUE THREAD

**Issue by frcepeda** [ITAM-DS/mate-computacional#161]
https://github.com/ITAM-DS/mate-computacional/blob/master/alumnos/LoreMD/Tareas/pruebaTarea.ipynb

Son literalmente 10 MB de output de un loop infinito. No podemos borrarlo y quitarlo de la historia o algo?

**Comment by nanounanue** [comment]
Deja checo

**Comment by nanounanue** [comment]
@LoreMD  voy a borrar ese archivo
