### ISSUE TITLE
Clase del 24 de Marzo, 2015

### ISSUE THREAD

**Issue by nanounanue** [ITAM-DS/mate-computacional#238]
@ITAM-DS/matecomputacional-2015 

Hola a todos

El día de mañana no habrá clase. Me enfermé desde el fin de semana de las vías respiratorias y al parecer se me está complicando. 

Por favor pueden avisarles a sus compañeros, para que nadie se levante temprano.

¿Qué proponen para reponer la clase?

**Comment by nanounanue** [comment]
@ITAM-DS/matecomputacional-2015 

¿Me pueden confirmar por aquí que sí se enteraron?

**Comment by JoseCopca** [comment]
Confirmo de enterado. Cuidese y mejórese.

**Comment by frcepeda** [comment]
(y)

**Comment by jdelgadome** [comment]
Enterado.
Espero se recupere pronto

Saludos,
Jorge Alfredo

**Comment by MariaJoseGonzalez** [comment]
Enter ads

**Comment by jajhalberto** [comment]
Enterado


Que te mejores, Adolfo






Enviado desde Correo de Windows





De: Adolfo De Unánue
Enviado el: ‎lunes‎, ‎23‎ de ‎marzo‎ de ‎2015 ‎09‎:‎51‎ ‎p. m.
Para: ITAM-DS/mate-computacional
CC: Alberto Jimenez





@ITAM-DS/matecomputacional-2015 

Hola a todos

El día de mañana no habrá clase. Me enfermé desde el fin de semana de las vías respiratorias y al parecer se me está complicando. 

Por favor pueden avisarles a sus compañeros, para que nadie se levante temprano.

¿Qué proponen para reponer la clase?

**Comment by Rodrigo163** [comment]
Enterado. 

RLPA

**Comment by manemarron** [comment]
Enterado prof. Que se mejore.

**Comment by terandes** [comment]
Enterada, que se recupere Profesor

**Comment by alonsogv** [comment]
Enterado

**Comment by YasminTC** [comment]
Enterada. Espero se recupere pronto!

Enviado desde mi iPhone

**Comment by mcarranzba** [comment]
Enterado. Espero se recupere pronto y no sufra mucho. Saludos.

**Comment by mreyesba** [comment]
Mejorese profe, nos vemos el jueves.
Date: Mon, 23 Mar 2015 20:52:22 -0700

**Comment by DiegoVillegasA** [comment]
Enterado profe. Cuídese, no se vuelva zombie :P

**Comment by MimiLimones** [comment]
Confirmo de enterada. Gracias por el aviso :) 
Que te mejores Adolfo!
Saludos!

**Comment by diegoteran** [comment]
Enterado. Que se mejore.

**Comment by nanounanue** [comment]
@ITAM-DS/matecomputacional-2015 

Hola a todos

Ya fuí al doctor y tengo infección viral/bacteriana de oido y garganta :-1:

Me mandaron muchas medicinas y reposo. Hoy no fuí al ITAM y mañana tampoco lo haré.

Pero el jueves nos vemos. **NO** olviden planear cuándo reponer la clase.

**Comment by YasminTC** [comment]
PROFE, lo lamento mucho y espero se mejore pronto.


Enviado desde mi iPhone

**Comment by iunnab** [comment]
Sí profesor, mejórese.
Tome té de propóleo, a mi me ayuda.

--- Исходное сообщение ---

От: "Adolfo De Unánue" <notifications@github.com>
Отправлено: 24 марта 2015 г. 14:03
Отправить по адресу: "ITAM-DS/mate-computacional" <mate-computacional@noreply.github.com>
Копия: "iunnab" <rushian_doll@hotmail.com>
Тема: Re: [mate-computacional] Clase del 24 de Marzo, 2015 (#238)

@ITAM-DS/matecomputacional-2015

Hola a todos

Ya fuí al doctor y tengo infección viral/bacteriana de oido y garganta :-1:

Me mandaron muchas medicinas y reposo. Hoy no fuí al ITAM y mañana tampoco lo haré.

Pero el jueves nos vemos. **NO** olviden planear cuándo reponer la clase.

---
