### ISSUE TITLE
Problemas para visualizar LaTex en los notebooks.

### ISSUE THREAD

**Issue by alonsogv** [ITAM-DS/mate-computacional#241]
Quise hacer cosas de esta materia pero en cuanto abro un nuevo notebook me aparece el siguiente mensaje:

Failed to retrieve MathJax from 'https://cdn.mathjax.org/mathjax/latest/MathJax.js'
Math/LaTeX rendering will be disabled.
If you have administrative access to the notebook server and a working internet connection, you can install a local copy of MathJax for offline use with the following command on the server at a Python or IPython prompt:
>>> from IPython.external import mathjax; mathjax.install_mathjax()

This will try to install MathJax into the IPython source directory.
If IPython is installed to a location that requires administrative privileges to write, you will need to make this call as an administrator, via 'sudo'.
When you start the notebook server, you can instruct it to disable MathJax support altogether:
$ ipython notebook --no-mathjax

which will prevent this dialog from appearing.

No sé si alguien me pueda ayudar o echar la mano, puesto que, como dice el título del issue, no puedo visualizar el formato tipo LaTex (si bien el resto de las paqueterías de IPyton siguen funcionando correctamente), y eso es terrible para las partes en las que se usa Cálculo Simbólico para resolver los problemas de clase y tareas

**Comment by nanounanue** [comment]
Al parecer estaba sobrecargado el servidor de `mathjax`... ¿Puedes probar de nuevo?

**Comment by alonsogv** [comment]
Ya lo intenté una terna de veces más...mismo mensaje y mismos problemas.

**Comment by nanounanue** [comment]
Apaga tu docker y préndelo de nuevo. Ese error se debe a que no te estas
pudiendo conectar al servidor de `mathjax` no tiene nada que ver con python

**Comment by alonsogv** [comment]
Ya se solucionó. Gracias por la ayuda :)
